django-mini-blog/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from blog import views
from blog.views import ArticleList
from django.conf import settings

urlpatterns = [
    url(r'^admin', include(admin.site.urls)),
    url(r'^$', ArticleList.as_view()),
    url(r'^post-comment', views.post_comment, name="post-comment")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.utils import formats


# Create your models here.

class Article(models.Model):
    def __str__(self):
        return self.title

    title = models.CharField(max_length=255)
    author = models.ForeignKey(User)
    content = RichTextField()
    dateCreated = models.DateTimeField(auto_now_add=True)
    dateUpdated = models.DateTimeField(auto_now=True)
    album = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ['-dateCreated']


class Comment(models.Model):
    def __str__(self):
        return self.firstname + ' ' + self.lastname + ' ' + str(
            formats.date_format(self.dateCreated, "SHORT_DATETIME_FORMAT"))

    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    content = models.TextField()
    dateCreated = models.DateTimeField(auto_now_add=True)
    dateUpdated = models.DateTimeField(auto_now=True)
    id_article = models.ForeignKey(Article)


class Image(models.Model):
    def __str__(self):
        return self.title
    title = models.CharField(max_length=100)
    path = models.ImageField()
    dateCreated = models.DateTimeField(auto_now_add=True)
    dateUpdated = models.DateTimeField(auto_now=True)
    id_article = models.ForeignKey(Article)

blog/views.py
from django.views.generic import ListView
from blog.models import Article, Comment
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib import messages


# One example of django built-in class based view. Very useful for list all elements from a model.
class ArticleList(ListView):
    model = Article
    paginate_by = 2


def post_comment(request):
    if request.method == 'POST':
        if request.POST['_firstname'] and request.POST['_lastname'] and request.POST['_content'] and request.POST['_id_article']:
            firstname = request.POST['_firstname']
            lastname = request.POST['_lastname']
            content = request.POST['_content']
            article = get_object_or_404(Article, id=request.POST['_id_article'])
            comment = Comment(firstname=firstname, lastname=lastname, content=content, id_article=article)
            comment.save()
            messages.add_message(request, messages.SUCCESS, "Votre commentaire a été posté avec succès.")
            return HttpResponseRedirect('/')
        else:
            messages.add_message(request, messages.ERROR,
                                 "Une erreur est survenue. Veuilliez réessayer plus tard ou contacter l'administrateur du site.", extra_tags='danger')
        return HttpResponseRedirect('/')
    else:
        messages.add_message(request, messages.ERROR,
                             "Une erreur est survenue. Veuilliez réessayer plus tard ou contacter l'administrateur du site.", extra_tags='danger')
        return HttpResponseRedirect('/')

blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="fr-fr" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | Nathan@Manipal</title>
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon-precomposed" href="images/apple-touch-icon.png">
    <link rel="stylesheet" href="{% static "blog/css/uikit.almost-flat.min.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/main.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/components/slideshow.min.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/components/slidenav.min.css" %}">
    {% block extracss %}{% endblock extracss %}

</head>

<body>

<div class="uk-container uk-container-center uk-margin-top uk-margin-large-bottom">

    <nav class="uk-navbar uk-margin-large-bottom">
        <ul class="uk-navbar-nav uk-hidden-small">
            {% block navbar %}
                <li {% if request.path = "/" %}class="uk-active"{% endif %}>
                    <a href="/">Accueil</a>
                </li>
            {% endblock navbar %}
        </ul>
    </nav>

    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-3-4">
            {% block body %}



                <article class="uk-article">

                </article>


            {% endblock body %}
        </div>

        <div class="uk-width-medium-1-4">
            {% block left_menu %}

                <div class="uk-panel uk-panel-box uk-text-center">
                    <img class="uk-border-rounded" width="120" height="120" src="{% static "blog/img/nathan.jpg" %}"
                         alt="">

                    <h3>Nathan Bigaignon</h3>

                    <p>&#201;tudiant en 4ème à Epitech. Actuellement en séjour d'étude à l'université de Manipal en
                        Inde.</p>
                </div>
                <div class="uk-panel">
                    <h3 class="uk-panel-title">Social</h3>
                    <ul class="uk-list">
                        <li><a href="https://github.com/epi-log">GitHub</a></li>
                        <li>
                            <a href="https://www.linkedin.com/pub/nathan-bigaignon/6a/525/743?trk=seokp_posts_secondary_cluster_res_author_photo">Linkedin</a>
                        </li>
                        <li><a href="https://www.facebook.com/nathan.bigaignon.9">Facebook</a></li>
                    </ul>
                </div>

            {% endblock left_menu %}
        </div>
    </div>

</div>
<script src="{% static "blog/js/jquery-2.1.4.min.js" %}"></script>
<script src="{% static "blog/js/uikit.min.js" %}"></script>
{% block extrajs %}{% endblock extrajs %}
</body>
</html>

blog/templates/blog/article_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Articles{% endblock %}
{% block breadcrumb %}
    <li><a href="/">Accueil</a></li>
    <li class="uk-active"><span>Articles</span></li>
{% endblock %}
{% block extracss %}
    <link rel="stylesheet" href="{% static "blog/css/components/slider.almost-flat.min.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/components/slidenav.almost-flat.min.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/article_list.css" %}">
{% endblock extracss %}
{% block body %}
    <div class="">
        {% if messages %}
            <ul class="uk-list">
                {% for message in messages %}
                    <li>
                        <div class="uk-alert uk-alert-{{ message.tags }}">{{ message }}</div>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        <article class="uk-article">
            {% for Article in object_list %}
                <h1 class="uk-article-title">
                    {{ Article.title }}
                </h1>

                <p class="uk-article-meta">Rédigé par {{ Article.author.first_name }} {{ Article.author.last_name }}
                    le {{ Article.dateCreated }}.</p>

                <p>{{ Article.content|safe }}</p>
                {% if Article.image_set.count != 0 %}
                    <div class="uk-panel-box uk-margin-bottom">
                        {% if Article.image_set.count > 2 %}
                            <div class="uk-slidenav-position"
                                 data-uk-slider{% if Article.image_set.count <= 2 %}="{center:true, infinite:false}"{% endif %}>

                                <div class="uk-slider-container">
                                    <ul class="uk-slider uk-grid-medium-1-4">
                                        {% for image in Article.image_set.all %}
                                            <li><img src="media/{{ image.path }}" height="250" width="250" alt=""></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                <a href="" class="uk-slidenav uk-slidenav-contrast uk-slidenav-previous"
                                   data-uk-slider-item="previous"></a>
                                <a href="" class="uk-slidenav uk-slidenav-contrast uk-slidenav-next"
                                   data-uk-slider-item="next"></a>
                            </div>
                        {% else %}
                            <div class="uk-grid">
                                {% for image in Article.image_set.all %}
                                    <div class="uk-width-1-2">
                                        <a href="media/{{ image.path }}" data-uk-lightbox="{group:'_group_{{ Article.id }}'}" title="{{ image.title }}"><img src="media/{{ image.path }}" alt=""></a>
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
                <button
                        class="uk-button uk-button-small uk-button-primary"
                        data-uk-modal="{target:'#_article_{{ Article.id }}'}"><span
                        class="uk-icon-plus uk-icon-mini"> Commenter cet article</span>
                </button>
                {% if Article.album != "" %}
                    <a href="{{ Article.album }}"
                       class="uk-button uk-button-small">
                        <span class="uk-icon-camera uk-icon-mini"> Voir les photos</span>
                    </a>
                {% endif %}
                <div id="_article_{{ Article.id }}" class="uk-modal">
                    <div class="uk-modal-dialog">
                        <div class="uk-modal-header">Poster un commentaire</div>
                        <form class="uk-form uk-form-stacked" method="post" action="/post-comment/">
                            <fieldset>
                                <div class="uk-form-row">
                                    <label for="_firstname" class="uk-form-label">Prénom</label>
                                    <input id="_firstname" name="_firstname" class="uk-form-width-large" type="text"
                                           required
                                           placeholder="">
                                </div>
                                <div class="uk-form-row">
                                    <label for="_lastname" class="uk-form-label">Nom</label>
                                    <input id="_lastname" name="_lastname" class="uk-form-width-large" type="text"
                                           required
                                           placeholder="">
                                </div>
                                <div class="uk-form-row">
                                    <label for="_content" class="uk-form-label">Contenu</label>
                                    <textarea id="_content" name="_content" class="uk-form-width-large uk-form-large"
                                              required
                                              rows="5"></textarea>
                                </div>
                            </fieldset>
                            <div class="uk-modal-footer">
                                <button class="uk-button-small uk-button uk-button-primary" type="submit">Poster
                                </button>
                                <button class="uk-button-small uk-button uk-modal-close">Annuler</button>
                            </div>
                            <input type="hidden" name="_id_article" value="{{ Article.id }}">
                            {% csrf_token %}
                        </form>
                    </div>
                </div>

                {% if Article.comment_set.count != 0 %}
                    <button data-uk-toggle="{target: '#_comment_{{ Article.id }}'}"
                            class="uk-button uk-button-small"><span
                            class="uk-icon-comments uk-icon-mini">&nbsp;Afficher les commentaires</span>
                    </button>
                    <ul class="uk-comment-list uk-hidden" id="_comment_{{ Article.id }}">
                        {% for comment in Article.comment_set.all %}
                            <li class="uk-comment">
                                <article class="uk-comment">
                                    <div class="uk-comment-header">
                                        <h4 class="uk-comment-title">{{ comment.firstname }} {{ comment.lastname }}</h4>

                                        <p class="uk-comment-meta">{{ comment.dateCreated }}</p>
                                    </div>
                                    <div class="uk-comment-body">{{ comment.content }}
                                    </div>
                                </article>
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}

            {% endfor %}

            {% if is_paginated %}
                <div class="">
                    <ul class="uk-pagination uk-margin-top">
                        {% if page_obj.has_previous %}
                            <li><a href="?page={{ page_obj.previous_page_number }}"><i
                                    class="uk-icon-angle-double-left"></i></a></li>
                        {% else %}
                            <li class="uk-disabled"><span><i class="uk-icon-angle-double-left"></i></span></li>
                        {% endif %}
                        <li class="uk-active"><span>{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>
                        </li>
                        {% if page_obj.has_next %}
                            <li><a href="?page={{ page_obj.next_page_number }}"><i
                                    class="uk-icon-angle-double-right"></i></a></li>
                        {% else %}
                            <li class="uk-disabled"><span><i class="uk-icon-angle-double-right"></i></span></li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        </article>
    </div>
    {% block extrajs %}
        <script src="{% static "blog/js/components/lightbox.min.js" %}"></script>
        <script src="{% static "blog/js/components/slider.min.js" %}"></script>
    {% endblock extrajs %}
{% endblock %}